Global:
  DefaultAmountOfSpawnerEggsYouNeed: 5
  # Entries under here must be lowercase.
  # Entries omitted from here will have the default
  # specified above.
  AmountOfSpawnerEggsYouNeed:
    creeper: 10
    skeleton: 1
  perMobPermissions: true
Messages:
  ChangeSpawner: '&2Spawnertype changed to %entity. Reconnect to see the change!'
  NotEnoughSpawnerEggs: '&cYou dont have enough %entity Eggs.'
  FailedSpawnerEggs: '&cFailed changing the spawner type!'
